import Hero from '@/components/Hero/Hero'
import NavBar from '@/components/NavBar/NavBar'
import QuoteBanner from '@/components/QuoteBanner/QuoteBanner'
import Testimonials from '@/components/Testimonials/Testimonials'
import WebsitePackageDetails from '@/components/WebsitePackageDetails/WebsitePackageDetails'
import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <Hero />
            <QuoteBanner />
            <WebsitePackageDetails />
            <Testimonials />
        </>
    )
}
